services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    command: sh -c "alembic -c infrastructure/db/alembic/alembic.ini upgrade head && gunicorn -k uvicorn.workers.UvicornWorker 'bootstrap.app_factory:create_app()' --workers 4 --bind 0.0.0.0:8000 --log-level info"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
